# Generated by Django 4.0.2 on 2022-02-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='quantity',
        ),
    ]
