# Generated by Django 4.0.2 on 2022-02-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_complete_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='complete',
        ),
    ]
