# Generated by Django 4.0.2 on 2022-02-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_shippingaddress_country_shippingaddress_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='transaction',
            new_name='transaction_id',
        ),
    ]
